#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'chef-client'
cookbook 'chef_gem'
cookbook 'logrotate'
cookbook 'netcat'
cookbook 'ntp'
cookbook 'ohai'
cookbook 'openssh',         path: 'vendor/openssh'
cookbook 'screen'
cookbook 'simple_iptables', 
  git: 'git://github.com/dcrosta/cookbook-simple-iptables.git'
cookbook 'sudo'
cookbook 'tmux'
cookbook 'user'

# manage groups with data bags
cookbook 'group',
  :github => 'bbg-cookbooks/chef-group'
cookbook 'yum',             path: 'vendor/yum'

# Practice Fusion specific
cookbook 'pf-identity',     path: 'vendor/pf-identity'

# Monitoring
cookbook 'newrelic_monitoring'
cookbook 'nagios'
# Custom
cookbook 'splunk-forwarder', path: 'vendor/splunk-forwarder'
cookbook 'splunk_cookbook',
  :github => 'bestbuycom/splunk_cookbook'

# Custom cookbook to install a NRPE (Nagios monitoring client)
cookbook 'nrpe',            path: 'vendor/nrpe'

# Ruby - v0.9.0 is latest stable (master branch is dev)
cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'

# Unix apps
cookbook 'apache2',         path: 'vendor/apache2'

# PHR
cookbook 'cake-base',       path: 'vendor/cake-base'
cookbook 'cake-unicorn',    path: 'vendor/cake-unicorn'
cookbook 'redisio',         
  git: 'git://github.com/brianbianco/redisio.git'
# Custom simple iptables cookbook
cookbook 'set-iptables',    path: 'vendor/set-iptables'
cookbook 'tesseract',       path: 'vendor/tesseract'

# Auth Service
cookbook 'memcached'
